logging:
  level:
    org.hibernate.SQL: debug
    root: INFO
    org.springframework.web: ERROR
    com.hexa.challenge.springboot.swagger: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
file: ./logs/application.log
spring:
  application:
    name: hexa
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://34.27.79.153:5432/postgres
    username: postgres
    password: jdk83dav
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-stacktrace: never
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 24h in millisecond
    expiration-time: 86400000
mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER