create table enterprises (id bigint generated by default as identity, membership_date timestamp(6), company_name varchar(255), cuit varchar(255), primary key (id));

create table enterprise_transfer_info (amount numeric(38,2), id_enterprise bigint, id_transfer bigint not null, transaction_date timestamp(6), credit_account varchar(255), debit_account varchar(255), primary key (id_transfer));

INSERT INTO enterprise_entity (id, cuit, razon, membership_date) VALUES
    (6, '3012345698721', 'Fanta', '2023-10-19T15:30:45.123');

INSERT INTO enterprise_entity (id, cuit, razon, membership_date) VALUES
    (11, '3012345698411', 'Power',  '2023-10-19T15:30:46.123');

INSERT INTO enterprise_entity (id, cuit, razon, membership_date) VALUES
    (7, '3012325698241', 'Dia',  '2023-10-19T15:30:47.123');

INSERT INTO enterprise_entity (id, cuit, razon, membership_date) VALUES
    (8, '3012145698601', 'Sonic',  '2023-10-19T15:30:48.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (8, '20000', '5',  '1255544468988774658715', '1655544468988774658714','2023-10-19T16:32:45.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (7, '21000', '8',  '1255544468988774658715', '1555544468988774658715','2023-10-19T16:33:46.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (2, '22000', '7',  '1255544468988774658715', '1455544468988774658717','2023-10-19T16:34:47.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (1, '26000', '7',  '1255544468988774658715', '1855544468988774658718','2023-10-19T16:35:49.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (9, '46000', '6',  '1555544468988774658715', '1955544468988774658718','2023-10-19T16:35:49.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (121, '46000', '2',  '1555544468988774658715', '1955544468988774658718','2024-10-19T16:35:49.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (111, '26000', '2',  '1255544468988774658715', '1855544468988774658718','2023-10-19T16:35:49.123');

INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (931, '41000', '1',  '1555544468988774658715', '1955544468988774658718','2024-10-19T16:35:49.123');
INSERT INTO enterprise_transfer_info_entity (id_transfer, amount, id_enterprise, debit_account, credit_account, transaction_date) VALUES
    (125, '46000', '6',  '1555544468988774658715', '1955544468988774658718','2024-10-19T16:35:49.123');